<?php

    namespace app\widgets\uLogin;

    use yii\base\Widget;

    class uLoginWidget extends Widget{
        private $params;

        public function init(){
            parent::init(); // TODO: Change the autogenerated stub
            $this->params = [
                'display'   => 'panel',
                'fields'    => 'first_name,last_name,email',
                'optional'  => '',
                'providers' => 'vkontakte,odnoklassniki,mailru,facebook',
                'hidden'    => 'twitter,google,yandex,livejournal,openid,lastfm,linkedin,liveid,soundcloud,steam',
                'redirect'  => ''
            ];
        }

        public function run(){
            return $this->render('uloginView', ['params' => $this->params]);
        }
    }